### ISSUE TITLE
[DMP CMS] Development of DMP CMS BE/FE: Phase 2

### ISSUE THREAD

**Issue by MohitNSamagra** [Code4GovTech/DMP-CMS-Backend-CRON#1]
**Goal:** As a part of the Phase 2 development, users will see a more comprehensive frontend with percentage completions and edge cases identified at the start of the sprint will be fixed and closed. The application will then be deployed on production servers.

**Acceptance Criteria:**
- [x] User to see weekly progress bars with a completion percentage -FE
- [x] Weekly updates and learnings to come under dropdowns -FE
- [x] Filtering relevant comment from list of all comments(weekly goals to come from mentor and weekly learnings to come from contributor) -BE
- [x] Total progress to be calculated out of 12 weeks even if all weeks are not present in comments; each week's % to be used to calculate total progress % (every week to have equal share) -BE
- [x] PRs linked from PR title -BE

**Comment by karntrehan** [comment]
v2 Contract: https://docs.google.com/document/d/1VM7l7_5p0bPzOuvaK2GgNusNjm2rVhfwaE6TgvJtFkY/edit#heading=h.6cvnx9z9kqod

**Comment by MohitNSamagra** [comment]
- Mentor and org names to be shown from db - added manually to db
- API error handling responses
- PR time-stamp to be stored in db

**Comment by MohitNSamagra** [comment]
- P2 frontend - Riya to get back

**Comment by MohitNSamagra** [comment]
- P2 frontend to be closed by Fri
- P2 backend to be closed by Wed

**Comment by MohitNSamagra** [comment]
- APIs v2 - Sasi to close by Wed

**Comment by karntrehan** [comment]
* v2 API closed by Sasi. 
* Weekly learnings to be markdown content. 
* v2 to be shared on dev server.

FE: 
* Remove deployment from Vercel.

**Comment by MohitNSamagra** [comment]
- error 500 changes @sasi2312 to close
- v2 to be deployed on dev
- FE to be closed today

**Comment by MohitNSamagra** [comment]
- BE closed
- FE closed
- PR merged
